version: "3"
services:
  redis:
    image: redis:alpine
  tgbot:
    build: .
    command: python -m tgbot.entrypoint run --token ${TG_TOKEN}
    volumes:
      - .:/app
    links:
      - redis
